#!/usr/bin/env node
// Generated by Meshly Build Station — do not edit by hand. Never blocks.
import { getActiveTask } from "./meshly-hooks-lib.mjs";

const CHECKLIST =
  "Meshly Build task lifecycle (mandatory for any code work): " +
  "get_my_tasks -> create_task if none -> move_task('To Do') -> start_task BEFORE editing -> " +
  "do the work -> complete_task (honest summary) -> report_context_feedback if you called " +
  "get_project_context -> report_token_usage. Only ONE task In Progress per project.";

try {
  const active = await getActiveTask();
  let ctx = CHECKLIST;
  if (active && active.has_active) {
    ctx += "\n\nIn-progress task here: " + active.task_id + " — " + active.title +
      ". Continue it, or complete_task before starting different work.";
  } else if (active && active.has_active === false) {
    ctx += "\n\nNo in-progress task in this project yet — create_task + start_task before editing code.";
  }
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: ctx },
  }));
} catch {
  // never block session start
}
